### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by alexdbk** [mmmonteiro/designethics#10]
'List of Langauge Codes' > 'List of Language Codes' ;)

**Comment by jwishnie** [comment]
wanna create a pull request to fix?

**Comment by jwishnie** [comment]
and thank you @alexdbk, good catch!

**Comment by alexdbk** [comment]
Don’t know how to do that 😅 New to github. :(

**Comment by jwishnie** [comment]
That's ok! I went ahead and fixed it. Thanks again for pointing it out.
