### ISSUE TITLE
New to GitHub

### ISSUE THREAD

**Issue by Tarsio25** [mmmonteiro/designethics#17]
Hi there,
hope to find you all well!!

I've been working on a translation to Portuguese.
Made a pull request, but IM not sure if I am missing something... please help!!

Do I need to edit the readme and include the link of my file?! It says i have no authorization...

Thanks,
Rui

**Comment by Tarsio25** [comment]
No I cant seem to find the edit to my pt_PT.md file!!! Ahahaha so lost here...

**Comment by jwishnie** [comment]
Hi Tarsio! GitHub definitely has a learning curve.

To contribute you want to `fork` the project into your own account, make changes, and then issue a `pull request` for us to merge your changes back into the main repository.

There is good help here (look at the topics under 'Bootcamp' first):
https://help.github.com/

**Comment by mmmonteiro** [comment]
Hey Rui,
If you're new to Github you can just paste the text into a comment and I'll take care of it.

**Comment by Tarsio25** [comment]
Hey,
thanks for the help...

I will finish the translation to Portuguese tomorrow and then ill try
again with the final text!
Have a good one!

Rui

**Comment by Tarsio25** [comment]
[PT_portuguese_Ethics in Desing_Mike Monteiro.docx](https://github.com/mmmonteiro/designethics/files/1841556/PT_portuguese_Ethics.in.Desing_Mike.Monteiro.docx)

Hi all,

this is a first draft of the Portuguese translation... some pieces and bits need a little bit more polish as some expressions are harder to translate! I'm also waiting for a second pair of eyes to give me a review on it, I will probably I should have the final translation by monday.

Have a great weekend!!
