### ISSUE TITLE
A designer welcomes a diverse and competitive field.

### ISSUE THREAD

**Issue by nukeop** [mmmonteiro/designethics#25]
1. Who are those people who have been "historically kept down" and "traditionally marginalized"? Where is it a tradition to marginalize them?

2. "Diversity leads to better outcomes and solutions. Diversity leads to better design." Are there studies supporting this claim?

**Comment by andri** [comment]
@nukeop Surely you have heard those terms many times before?

Diversity means love and caring about marginalized people. When you include a broad range of people from different backgrounds in your work or project you are more likely to arrive at a good creative solution that takes into account the needs of society as a whole. For an example, there are plenty of studies that show that companies with women in leadership positions out do their competition. Remember, diversity is not only sex, but economic status, ethnicity and a range of other factors that make us into what we are.

https://www.mckinsey.com/~/media/mckinsey/business%20functions/organization/our%20insights/why%20diversity%20matters/diversity%20matters.ashx

**Comment by nukeop** [comment]
I think that study lacks an examination of countries where marginalization and oppression of huge groups on scales unheard of in Europe or USA is prominent but that thrive nonetheless, such as China. It is also very speculative and uses these speculations as a basis for concrete conclusions as though they were a fact, which is manipulative.

What I'm saying is that the document in this repository is oriented towards the Western sentiments and values. Monocultural teams are often fund to be outperforming mixed teams - China, Russia, India, and some Eastern European countries are often found among winners of programming competitions.

**Comment by mmmonteiro** [comment]
Closing this because it’s ignorant.

**Comment by nukeop** [comment]
That is why I formed the initial question, to become informed on the issue and stop being ignorant of possible information.

Your own document states: "Asking why is a design skill. Rolling your eyes is not." and also "A designer [...] is aware of their own biases and welcomes having them checked". Why not answer a legitimate question?

**Comment by Heatherwalls** [comment]
Why not educate yourself?

**Comment by jwishnie** [comment]
@nukeop following up on @Heatherwalls, here are a couple of starting points for your research:
http://bfy.tw/HHXg
http://bfy.tw/HHXW

**Comment by nukeop** [comment]
@Heatherwalls 
May I use a quote from the document here as it captures what I have to say better than anything I could have put together myself (and is wonderfully ironic, considering that the author does the exact opposite):

> A designer welcomes criticism.

> No code of ethics should protect your work from criticism, be it from clients, the public, or other designers. Instead, you should encourage criticism in order to create better work in the future. If your work is so fragile that it can’t withstand criticism it shouldn’t exist. The time to kick the tires on your work comes before those tires hit the road. And be open to that criticism coming from anywhere.

> The role of criticism, when given appropriately, is to evaluate and improve work. Criticism is a gift. It makes good work better. It keeps bad work from seeing the light of day.

> Criticism should be asked for and welcomed at every step of the design process. You can’t fix a cake once it’s been baked. But you can increase the chances your project is successful by getting feedback early and often. It’s your responsibility to ask for criticism.

**Comment by jwishnie** [comment]
@nukeop I am confused--how does demanding that people explain to you something that is easily learnable on your own a form of criticism?

Your comments come across to me as, well I will use a Tweet as it captures what I have to say better than anything I could:
https://twitter.com/knguyen/status/977333215701553152

**Comment by nukeop** [comment]
Let me ignore your disgusting racism and highlight the most relevant sentence in the above passage that I also agree with 100%:

> If your work is so fragile that it can’t withstand criticism it shouldn’t exist.

**Comment by jwishnie** [comment]
Hahaha. Sea lion! "Let me make an ad hominem attack in a statement that says I'm gonna ignore ad hominem attacks" -- you know, like when some jacka** says "I don't want to tell you I told you so... buuuut..."

Can we just cut to the chase and call each other poo poo heads and then you go away?

I'll start: you are a poo poo head

**Comment by nukeop** [comment]
Please leave.
